# Scikit usage
Pandas + Scikit trial learn

Using the Columns :
* precipitation
* temp_max
* temp_min
* wind
We are going to predict the weather condition :
* drizzle
* rain
* sun
* snow
* fog




In [2]:
import numpy

# Open dataset
data = open("./dataset/seattle-weather.csv", "r")

# First line is the feature names
# No need for weather since weather will be the target names
featureNames = data.readline()[:-1].split(",")[:-1]

# Labels for each dataset
targetNames = numpy.array(["drizzle", "rain", "snow", "fog"])

# Turn csv into array format
sortedData = []
targets = []
for line in data:
    # Remove /n from the end of the line
    line = line[:-1]
    # Get target names (the last section of code)
    lineList = line.split(",")
    # Convert to numeric values
    # Convert date
    lineList[0] = "".join([char for char in lineList[0] if char.isdigit()])
    # Add targets
    targets.append(lineList[-1])
    # Convert the rest
    # Skip the weather
    lineList = [float(value) for value in lineList[:-1]]
    sortedData.append(lineList)

# Turn targetNames into numpy array
targets = numpy.array(targets)
sortedData = numpy.array(sortedData)

print(targets)
print(sortedData)
print(featureNames)

# Array first axis = samples, second axis = features  

# Split the data into a 70-30 train to test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(sortedData, targets, test_size = 0.3, random_state = 1)

# Verify shape
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)







['drizzle' 'rain' 'rain' ... 'fog' 'sun' 'sun']
[[ 2.0120101e+07  0.0000000e+00  1.2800000e+01  5.0000000e+00
   4.7000000e+00]
 [ 2.0120102e+07  1.0900000e+01  1.0600000e+01  2.8000000e+00
   4.5000000e+00]
 [ 2.0120103e+07  8.0000000e-01  1.1700000e+01  7.2000000e+00
   2.3000000e+00]
 ...
 [ 2.0151229e+07  0.0000000e+00  7.2000000e+00  6.0000000e-01
   2.6000000e+00]
 [ 2.0151230e+07  0.0000000e+00  5.6000000e+00 -1.0000000e+00
   3.4000000e+00]
 [ 2.0151231e+07  0.0000000e+00  5.6000000e+00 -2.1000000e+00
   3.5000000e+00]]
['date', 'precipitation', 'temp_max', 'temp_min', 'wind']
(1022, 5)
(439, 5)
(1022,)
(439,)


Predict the data

In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
# Finding accuracy by comparing actual response values(y_test)with predicted response value(y_pred)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
# Providing sample data and the model will make prediction out of that data
from sklearn import svm
svc = svm.SVC(kernel='sigmoid')
svc.fit(X_train, y_train)

y_pred = svc.predict(X_test)

print(f"Accuracy SVC: {metrics.accuracy_score(y_test, y_pred)}")



Accuracy: 0.6400911161731208
Accuracy SVC: 0.4305239179954442


In [4]:
# New purpose

import numpy

# Open dataset
data = open("./dataset/seattle-weather.csv", "r")

# First line is the feature names
# No need for weather since weather is string
# Precipitation will be used as target
featureNames = data.readline()[:-1].split(",")[:-1]
targetName = featureNames.pop(1)

# Turn csv into array format
# Sorted data is the other data aside from the precipiation each day
sortedData = []
# Targets will be the precipitation of each day
targets = []
for line in data:
    # Remove /n from the end of the line
    line = line[:-1]
    # Get target names (the last section of code)
    lineList = line.split(",")
    # Convert to numeric values
    # Convert date
    lineList[0] = "".join([char for char in lineList[0] if char.isdigit()])
    # Convert the rest
    # Skip the last value since its weather
    # Use everything for data except the weather since weather are words
    lineList = [float(value) for value in lineList[:-1]]
    # Add target(dates) to the targets list
    precipitaion = lineList.pop(1)
    targets.append(precipitaion)
    # Add everything back to the data
    sortedData.append(lineList)

# Turn lists into numpy array
targets = numpy.array(targets)
sortedData = numpy.array(sortedData)

print(targets)
print(sortedData)
print(featureNames)

# Array first axis = samples, second axis = features  


# Split the data into a 70-30 train to test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(sortedData, targets, test_size = 0.3, random_state = 1)

# Verify shape
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)







[ 0.  10.9  0.8 ...  0.   0.   0. ]
[[ 2.0120101e+07  1.2800000e+01  5.0000000e+00  4.7000000e+00]
 [ 2.0120102e+07  1.0600000e+01  2.8000000e+00  4.5000000e+00]
 [ 2.0120103e+07  1.1700000e+01  7.2000000e+00  2.3000000e+00]
 ...
 [ 2.0151229e+07  7.2000000e+00  6.0000000e-01  2.6000000e+00]
 [ 2.0151230e+07  5.6000000e+00 -1.0000000e+00  3.4000000e+00]
 [ 2.0151231e+07  5.6000000e+00 -2.1000000e+00  3.5000000e+00]]
['date', 'temp_max', 'temp_min', 'wind']
(1022, 4)
(439, 4)
(1022,)
(439,)


# Test the svm

In [23]:
tmp_x_train = [[1.0,1.1], [0.2,0.3]]
tmp_y_train = ["hello","people"]

from sklearn import svm
svc = svm.SVC(kernel='sigmoid')
svc.fit(tmp_x_train, tmp_y_train)

SVC(kernel='sigmoid')

In [6]:
# Maybe in the future develop prediction for precipitation level with model that accepts models


